version: "3.9"

services:
  sample_project_101:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample_project_101
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: >
      sample_project_101
