name: Build and Deploy Docker Image

on:
    workflow_dispatch: {}
    release:
        types: [published]
        branches: [main]

env:
    DOCKER_IMAGE: deepak93p/sample_project_101 # Replace with your DockerHub image
    AZURE_WEBAPP_NAME: sample-project-101-app # Replace with your Azure Web App name
    AZURE_WEBAPP_RG: sample-project-101-rg # Replace with your Azure Web App resource group

jobs:
    build-push-docker-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              env:
                  DOCKER_USER: deepak93p
                  DOCKER_PWD: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
              run: echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

            - name: Build and Push Docker Image
              run: make docker-build-and-push IMAGE=${{ env.DOCKER_IMAGE }} TAG=${{ github.sha }}

            - name: Clean up Docker system
              run: docker system prune -f

    deploy:
        runs-on: ubuntu-latest
        needs: build-push-docker-image
        environment:
            name: "production"

        steps:
            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy to Azure Container Apps
              run: |
                  az containerapp update \
                    --name ${{ env.AZURE_WEBAPP_NAME }} \
                    --resource-group ${{ env.AZURE_WEBAPP_RG }} \
                    --image index.docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
                    --query "properties.configuration.ingress.fqdn" \
                    -o tsv
