name: Version Bump and Create Release

on:
    workflow_dispatch:
        inputs:
            bump_type:
                description: "Type of version bump"
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    bump-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up the environment
              uses: ./.github/actions/setup-poetry-env
              with:
                  python-version: "3.12"

            - name: Configure Git
              run: |
                  git config --global user.name 'GitHub Actions'
                  git config --global user.email 'actions@github.com'

            - name: Bump Version
              run: |
                  poetry run bump-my-version bump ${{ github.event.inputs.bump_type }}

            - name: Push changes
              run: |
                  git push
                  git push --tags

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  generate_release_notes: true
                  tag_name: ${{ github.ref_name }}
